{{/*
Shared logic. Two conventions used throughout:

  • BY-NAME RESOLUTION — `contentRepo`, `chartRepo`, `charts[].repo` and `credentials` are keys into
    `.Values.repositories` / `.Values.credentials`. Every lookup goes through a helper that `fail`s with
    the offending key, so a typo stops the render instead of producing a half-wired object.

  • GOTEMPLATE PASS-THROUGH — an ApplicationSet template contains ArgoCD goTemplate expressions, which
    look exactly like Helm actions. They are emitted as STRING LITERALS through `printf`: Go's lexer
    consumes a quoted string atomically, so `{{ }}` inside one is text, never an action. The same helpers
    therefore serve an Application by receiving static strings in place of those expressions.
*/}}

{{/* Labels carried by every object this chart renders. */}}
{{- define "chargo.labels" -}}
app.kubernetes.io/managed-by: chargo
platform: {{ .Values.global.platform }}
{{- end -}}

{{/*
Object name: <name|key>-<platform>. The platform suffix is not optional — two platforms sharing one ArgoCD
instance would otherwise collide on the object name.
ctx: root, key, entry
*/}}
{{- define "chargo.objectName" -}}
{{- printf "%s-%s" (.entry.name | default .key) .root.Values.global.platform -}}
{{- end -}}

{{/* Resolve a repository entry to its URL. ctx: root, key, ref (name of the referencing object) */}}
{{- define "chargo.repoURL" -}}
{{- $r := index (.root.Values.repositories | default dict) .key -}}
{{- if not $r -}}
{{- fail (printf "chargo: %s references repository %q, which is not declared in .Values.repositories" .ref .key) -}}
{{- end -}}
{{- $r.url | required (printf "chargo: repository %q has no url" .key) -}}
{{- end -}}

{{/*
Normalised chart list, as a JSON array the caller reads back with `fromJsonArray`. Each element:
{url, chart, version, releaseName, valueFiles}. `chartRepo`/`chartVersion` are the single-chart shorthand.

`releaseName` defaults to the app prefix rather than to the chart name: every App generated by one object
then shares it, which is what the charts deployed today already assume — we-chart qualifies its object
names with `global.app`, so two releases in one namespace stay distinct. Overridable per chart entry.
ctx: root, key, entry
*/}}
{{- define "chargo.chartList" -}}
{{- $root := .root -}}
{{- $e := .entry -}}
{{- $app := $e.app | default .key -}}
{{- $specs := $e.charts | default list -}}
{{- if and (not $specs) $e.chartRepo -}}
{{- $specs = list (dict "repo" $e.chartRepo "version" ($e.chartVersion | default "")) -}}
{{- end -}}
{{- $out := list -}}
{{- range $c := $specs -}}
{{- $r := index ($root.Values.repositories | default dict) $c.repo -}}
{{- if not $r -}}
{{- fail (printf "chargo: %s references chart repository %q, which is not declared in .Values.repositories" $.key $c.repo) -}}
{{- end -}}
{{- if ne ($r.type | default "git") "helm" -}}
{{- fail (printf "chargo: %s references %q as a chart repository, but it is declared type %q" $.key $c.repo ($r.type | default "git")) -}}
{{- end -}}
{{- $chart := $r.name | default $c.repo -}}
{{- $version := $c.version | default $r.version | default "" -}}
{{- if not $version -}}
{{- fail (printf "chargo: %s uses chart %q without a version — set it on the object (chartVersion / charts[].version) or on the repository" $.key $chart) -}}
{{- end -}}
{{- $out = append $out (dict
      "url" $r.url
      "chart" $chart
      "version" $version
      "releaseName" ($c.releaseName | default $app)
      "valueFiles" ($c.valueFiles | default $e.discovery.valueFiles | default (list "values.yaml"))) -}}
{{- end -}}
{{- $out | toJson -}}
{{- end -}}

{{/*
Stacked valueFiles for one chart, lowest precedence first. Each file is ignored if absent
(`ignoreMissingValueFiles`), so a level that does not exist simply contributes nothing:

  <shared>/<f>  <  <overlay>/<f>  <  <every prefix of the leaf>/<shared>/<f>  <  <leaf>/<f>

`prefixes` walks the leaf path one segment at a time, so a `_shared` sits at EVERY level of the tree:
dev/_shared then dev/blue/_shared for a leaf at dev/blue/election.

ctx: files, shared, overlays, prefixes, pathExpr — `prefixes` and `pathExpr` are goTemplate expressions
for an ApplicationSet, and plain paths for an Application.
*/}}
{{- define "chargo.valueFiles" -}}
{{- $ctx := . -}}
{{- range $f := .files }}
- $values/{{ $ctx.shared }}/{{ $f }}
{{- range $o := $ctx.overlays }}
- $values/{{ $o }}/{{ $f }}
{{- end }}
{{- range $p := $ctx.prefixes }}
- $values/{{ $p }}/{{ $ctx.shared }}/{{ $f }}
{{- end }}
- $values/{{ $ctx.pathExpr }}/{{ $f }}
{{- end }}
{{- end -}}

{{/*
The spec shared by both kinds — `ApplicationSet.spec.template.spec` and `Application.spec` are the same
object. Emitted unindented; the caller applies `nindent`.

ctx: root, key, entry, mode ("set" | "app")
*/}}
{{- define "chargo.appSpec" -}}
{{- $root := .root -}}
{{- $e := .entry -}}
{{- $set := eq .mode "set" -}}
{{- $app := $e.app | default .key -}}
{{- $disc := $e.discovery | default dict -}}
{{- $shared := $disc.shared | default "_shared" -}}
{{- $content := include "chargo.repoURL" (dict "root" $root "key" ($e.contentRepo | required (printf "chargo: %s has no contentRepo" .key)) "ref" .key) -}}
{{- $revision := $e.revision | default $root.Values.global.revision -}}
{{- /* WHERE THE CHART COMES FROM — one question, one key. Declaring chart coordinates under a source type
       that does not read them is an error rather than a silent no-op: believing you steer a version that
       nobody reads is worse than being told. */ -}}
{{- $src := $e.sourceType | default "registryChart" -}}
{{- if not (has $src (list "registryChart" "gitChart" "directory")) -}}
{{- fail (printf "chargo: %s has sourceType %q — expected registryChart, gitChart or directory" .key $src) -}}
{{- end -}}
{{- if and (ne $src "registryChart") (or $e.chartRepo $e.charts $e.chartVersion) -}}
{{- fail (printf "chargo: %s declares chart coordinates but its sourceType is %q, which reads them from the content repository instead" .key $src) -}}
{{- end -}}
{{- $releaseName := $e.releaseName | default (ternary "{{ .path.basename }}" ($e.app | default .key) $set) | quote -}}
{{- /* Path of the leaf, and every prefix of it that can carry a <shared> directory. goTemplate expressions
       for a set, plain paths otherwise.
       `min` is what keeps the expression safe: for a leaf shallower than `depth`, the prefix collapses to
       the leaf path itself, which yields a <leaf>/<shared> that simply does not exist. Without it, `slice`
       would run past the end of .path.segments and abort the generator. */ -}}
{{- $depth := int ($disc.depth | default 4) -}}
{{- $pathExpr := "" -}}
{{- $prefixes := list -}}
{{- if $set -}}
{{- $pathExpr = "{{ .path.path }}" -}}
{{- range $i := until $depth -}}
{{- $prefixes = append $prefixes (printf "{{ join \"/\" (slice .path.segments 0 (min %d (len .path.segments))) }}" (add1 $i)) -}}
{{- end -}}
{{- else -}}
{{- $pathExpr = ($e.path | required (printf "chargo: application %s has no path" .key)) -}}
{{- $segs := splitList "/" $pathExpr -}}
{{- range $i := until (min $depth (len $segs) | int) -}}
{{- $prefixes = append $prefixes (join "/" (slice $segs 0 (add1 $i))) -}}
{{- end -}}
{{- end -}}
{{- /* Destination namespace. Pinned by `namespace:` on the object — the only way to reach it when the
       content carries no leaf file to read one from, as with raw manifests. Otherwise derived, with a
       leaf-level override. The fallback is built with goTemplate's own `printf`: a nested `{{ }}` inside a
       goTemplate string would never be evaluated. */ -}}
{{- $ns := "" -}}
{{- if $e.namespace -}}
{{- $ns = $e.namespace -}}
{{- else if $set -}}
{{- $basis := ternary ".path.basename" "(index .path.segments 0)" (eq $e.naming "basename") -}}
{{- $ns = printf "{{ dig \"namespace\" \"\" . | default (printf \"%s-%%s\" %s) }}" $app $basis -}}
{{- else -}}
{{- $ns = printf "%s-%s" $app (splitList "/" $pathExpr | first) -}}
{{- end -}}
{{- /* Application version displayed by ArgoCD, distinct from the chart version. Read from the leaf inside
       a set; taken from the object elsewhere. `dig` yields "" when the key is absent. */ -}}
{{- $versionLabel := ternary "{{ dig \"global\" \"version\" \"\" . }}" ($e.version | default "") $set -}}
project: {{ $e.project | default .key }}
{{- if $versionLabel }}
info:
  - name: app-version
    value: '{{ $versionLabel }}'
{{- end }}
{{- if eq $src "directory" }}
{{- /* Applied exactly as committed, `recurse` picking up the subdirectories. No value stacking — that is
       a helm feature — and no pull secret injection: a raw podspec carries its own imagePullSecrets. */}}
source:
  repoURL: {{ $content }}
  targetRevision: {{ $revision }}
  path: '{{ $pathExpr }}'
  directory:
    recurse: true
{{- else if eq $src "gitChart" }}
{{- /* The leaf directory IS the chart: it carries a Chart.yaml, and ArgoCD resolves its `dependencies`
       with `helm dependency build`. A PRIVATE dependency repository must appear in `repositories` —
       that entry is what the repo-server authenticates with; a public one needs nothing.
       Two sources on the same repository: one renders the chart at `path`, the other is mounted as
       `$values` so the stacked overlays outside the chart directory stay reachable. Note that the leaf's
       own values.yaml is already the chart's defaults — listing it again changes nothing. */}}
sources:
  - repoURL: {{ $content }}
    targetRevision: {{ $revision }}
    path: '{{ $pathExpr }}'
    helm:
      ignoreMissingValueFiles: true
      releaseName: {{ $releaseName }}
      valueFiles:
        {{- include "chargo.valueFiles" (dict "files" ($disc.valueFiles | default (list "values.yaml")) "shared" $shared "overlays" ($disc.overlays | default list) "prefixes" $prefixes "pathExpr" $pathExpr) | trim | nindent 8 }}
  - repoURL: {{ $content }}
    targetRevision: {{ $revision }}
    ref: values
{{- else }}
{{- /* N charts in ONE object, each with its own FLAT values files, where an umbrella Chart.yaml would
       nest every file under a subchart key. */}}
{{- $charts := include "chargo.chartList" (dict "root" $root "key" .key "entry" $e) | fromJsonArray }}
{{- if not $charts }}
{{- fail (printf "chargo: %s has sourceType registryChart but declares no chart (set chartRepo or charts)" .key) }}
{{- end }}
sources:
{{- range $c := $charts }}
  - repoURL: {{ $c.url }}
    chart: {{ $c.chart }}
    targetRevision: {{ $c.version | quote }}
    helm:
      {{- /* Static, not read from the leaf: N charts share one App, so a leaf-level override would give
             them all the same release name. */}}
      ignoreMissingValueFiles: true
      releaseName: {{ $c.releaseName | quote }}
      valueFiles:
        {{- include "chargo.valueFiles" (dict "files" $c.valueFiles "shared" $shared "overlays" ($disc.overlays | default list) "prefixes" $prefixes "pathExpr" $pathExpr) | trim | nindent 8 }}
{{- end }}
  - repoURL: {{ $content }}
    targetRevision: {{ $revision }}
    ref: values
{{- end }}
destination:
  server: {{ $root.Values.global.clusterServer }}
  {{- /* Several leaves may share a namespace: we-chart qualifies its Service selectors with global.app,
         so their workloads stay distinct. */}}
  namespace: '{{ $ns }}'
syncPolicy:
  {{- /* The label is the hook an external-secrets namespaceSelector uses to reach namespaces created
         after this chart was rendered. */}}
  managedNamespaceMetadata:
    labels:
      gitops-app: {{ $app }}
  {{- toYaml ($e.syncPolicy | default dict) | nindent 2 }}
{{- end -}}

{{/*
metadata of the generated App: name, finalizer, labels. Emitted unindented.
ctx: root, key, entry, mode
*/}}
{{- define "chargo.appMetadata" -}}
{{- $root := .root -}}
{{- $e := .entry -}}
{{- $set := eq .mode "set" -}}
{{- $app := $e.app | default .key -}}
{{- /* The finalizer prunes an App's workloads when the App object is deleted. Inside a set that happens
       when a LEAF disappears from the content repository, which is the intended GitOps behaviour. A
       standalone Application is deleted when its VALUES ENTRY disappears — an ops edit, not a content
       change — so it carries no finalizer unless `cascadeDelete: true` asks for one explicitly. */ -}}
{{- $cascade := dig "cascadeDelete" (ternary $root.Values.global.cascadeDelete false $set) $e -}}
{{- $name := "" -}}
{{- if $set -}}
{{- $name = ternary (printf "%s-{{ .path.basename }}" $app) (printf "%s-{{ .path.path | replace \"/\" \"-\" }}" $app) (eq $e.naming "basename") -}}
{{- else -}}
{{- $name = include "chargo.objectName" (dict "root" $root "key" .key "entry" $e) -}}
{{- end -}}
name: '{{ $name }}'
{{- if $cascade }}
{{- /* Removing the leaf from the content repository deletes the App and prunes its resources. */}}
finalizers:
  - resources-finalizer.argocd.argoproj.io
{{- end }}
{{- /* Labels of the ArgoCD card; values must be label-safe. Read FROM THE LEAF, which the git generator
       is the only thing to parse — a value living in <shared> is invisible here, so the default applies. */}}
labels:
  app: '{{ ternary (printf "{{ dig \"global\" \"app\" \"%s\" . }}" $app) $app $set }}'
  platform: {{ $root.Values.global.platform }}
  {{- /* Inside a set the leaf supplies it, and `dig` leaves the label empty when it does not. Outside one
         there is no leaf to read, so the label is omitted rather than emitted empty. */}}
  {{- if $set }}
  version: '{{ "{{ dig \"global\" \"version\" \"\" . }}" }}'
  {{- else if $e.version }}
  version: {{ $e.version | quote }}
  {{- end }}
{{- end -}}

{{/*
Placeholder resolved by EXTERNAL-SECRETS, not by Helm: `{{ .<secretKey> }}` referring to an entry of
spec.data. ctx: the secretKey.
*/}}
{{- define "chargo.esoRef" -}}
{{- printf "{{ .%s }}" . -}}
{{- end -}}

{{/*
Resolve an identity. ctx: root, key, ref

Each field is EITHER a literal string OR a pointer into the secret store. The shape decides how the
credential is delivered, so nothing has to be declared twice:

    username: CAPTAIN_RIMAFLOWA              literal, ends up in the Secret as written
    password: {key: …, property: …}          pointer, external-secrets fetches it

A pointer uses external-secrets' own field names — `key` for the entry in the store, `property` for the
field inside it — so it transposes to a `remoteRef` unchanged. `property` defaults to the credential half
it belongs to.

A credential mixing the two is normal and useful: an account name is not secret, its token is. The
credential then renders as one ExternalSecret carrying the literal in its template and fetching only what
is actually secret.

Returns {external: bool, fields: {username|password: {ref, value|key, property, version}}} as JSON.
*/}}
{{- define "chargo.credentials" -}}
{{- $c := index (.root.Values.credentials | default dict) .key -}}
{{- if not $c -}}
{{- fail (printf "chargo: %s references credentials %q, which is not declared in .Values.credentials" .ref .key) -}}
{{- end -}}
{{- $out := dict "external" false "fields" (dict) -}}
{{- range $f := list "username" "password" -}}
{{- $v := index $c $f -}}
{{- if kindIs "map" $v -}}
{{- $_ := set $out.fields $f (dict "ref" true
      "key" ($v.key | required (printf "chargo: credentials %q, %s: a pointer needs a `key`" $.key $f))
      "property" ($v.property | default $f)
      "version" ($v.version | default "")) -}}
{{- $_ := set $out "external" true -}}
{{- else if $v -}}
{{- $_ := set $out.fields $f (dict "ref" false "value" (toString $v)) -}}
{{- else -}}
{{- fail (printf "chargo: credentials %q has no %s — give it a string, or a {key, property} pointer" $.key $f) -}}
{{- end -}}
{{- end -}}
{{- $out | toJson -}}
{{- end -}}
